---
# handlers file for docker
- name: Start docker
  service: name=docker state=started

- name: Reload docker
  service: name=docker state=reloaded

- name: Restart docker
  systemd: name=docker state=restarted daemon_reload=yes
